Theme config does not take effect
fossasia/eventyay-video pull request #155
Opened 2024-07-16 08:23 UTC by lcduong

> Fixes [#137 Theme config does not take effect](https://github.com/fossasia/eventyay-video/issues/137)
> 
> #### Short description of what this resolves:
> Theme config does not take effect
> 
> #### Changes proposed in this pull request:
> * Update theme.config.colors with colors data from API response
> 
> #### Checklist
> * [x]  I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
> * [x]  My branch is up-to-date with the Upstream `development` branch.
> * [ ]  The acceptance, integration, unit tests and linter pass locally with my changes
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  I have added necessary documentation (if appropriate)

2024-07-16 08:26 UTC, lcduong commented
![image](https://github.com/user-attachments/assets/11676bfc-513f-421d-85ff-9f344cbffa0b)


Note: for upload logo file, [urls] [media] must be configured in config file
e.g:
[urls]
media=http://localhost:8443/media/

since /media is expose by server app, so need to config nginx for expose via webapp.

2024-07-17 10:15 UTC, hongquan requested changes

2024-07-17 10:15 UTC, hongquan commented on server/venueless/zoom/views.py
> +        world_domain = re.sub(r":\d+$", "", self.request.headers["Host"])
Please use Django's built-in `request.get_host()`.

2024-07-17 10:15 UTC, hongquan commented on server/venueless/api/views.py
> +        return Response(WorldSerializer(world).data['config']['theme'])
Please handle `KeyError`.

2024-07-17 10:22 UTC, hongquan commented
I think it is not safe to assume that the API response is always in the shape that the frontend expects (like missing some fields, or different data type).
It is better to go through a "validation step" (using https://docs.superstructjs.org/ or https://zod.dev/). This process will show us (developers) how the API is unmatched, so that we can fix frontend, or backend code easier. But I'm not sure if we should require our frontend developers to apply this practice (I feel it is a bit advance).

In the future, we can migrate our frontend to Vue 3 + TypeScript, this "validation step" will be mandatory, because not only it help developers to find where data is wrong, but also provide type information (TypeScript) for IDE to produce good autocomplete.

2024-07-17 10:53 UTC, hongquan requested changes

2024-07-17 10:53 UTC, hongquan commented on server/venueless/api/views.py
> +        except KeyError:
If `KeyError` happens, it means that us, the website owner, did not prepare enough data, or misconfigured the website. We need to do `logger.error` to inform our team.

For end user, we can throw error 503 to tell that this error is our side, temporary and can work again in the future.

2024-07-20 12:28 UTC, hongquan requested changes

2024-07-20 12:28 UTC, hongquan commented on server/venueless/api/views.py
> +            logger.error(f"error happened when trying to get theme data of world: " + kwargs["world_id"])
Incorrect use of logger. Check guide in https://github.com/fossasia/eventyay-talk/pull/130

2024-07-22 06:09 UTC, hongquan approved these changes

2024-07-22 06:20 UTC, merged