Enhance Chat Mentions
fossasia/eventyay-video pull request #156
Opened 2024-07-16 09:37 UTC by odkhang

> Fixes [#138  Enhance Chat Mentions](https://github.com/fossasia/eventyay-video/issues/138)
> 
> #### Short description of what this resolves:
> Implement @username mentions in the chat 
> 
> #### Changes proposed in this pull request:
> * Implement @username mentions in the chat
> 
> #### Checklist
> * [x]  I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
> * [x]  My branch is up-to-date with the Upstream `development` branch.
> * [ ]  The acceptance, integration, unit tests and linter pass locally with my changes
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  I have added necessary documentation (if appropriate)

2024-07-17 07:31 UTC, hongquan requested changes

2024-07-17 07:31 UTC, hongquan commented on server/tests/live/test_auth.py
> +
Please configure your editor to automatically clean trailing whitespaces (at the end of line).

2024-07-17 07:31 UTC, hongquan commented on server/tests/live/test_chat.py
> +
Clean trailing whitespaces, too.

2024-07-17 07:31 UTC, hongquan commented on server/tests/live/test_chat_direct.py
> +
2 blank lines between functions, classes (PEP8 coding style).

2024-07-17 07:35 UTC, hongquan commented on server/venueless/core/migrations/0065_alter_auditlog_data_alter_chatevent_content_and_more.py
> +            model_name="auditlog",
Why are there migrations relatd to `AuditLog` model? I don't see changes of `AuditLog` model in this PR.

2024-07-18 01:49 UTC, odkhang commented
Hi @hongquan, 
I removed unintended changes in the AuditLog model by deleting the incorrect migration file and regenerating the migrations. Now, the new migration file only includes the intended updates.
Please review the updated migrations.

2024-07-21 07:12 UTC, hongquan approved these changes

2024-07-21 07:25 UTC, merged